cd ./bch_dec/decoder128/build-rvt
make clean
cd ../../../bch_dec/decoder32/build-rvt
make clean
cd ../../../bch_dec/decoder64/build-rvt
make clean
cd ../../../bch_dec/encoder128/build-rvt
make clean
cd ../../../bch_dec/encoder32/build-rvt
make clean
cd ../../../bch_dec/encoder64/build-rvt
make clean
cd ../../../sec_ded/encoder128/build-rvt
make clean
cd ../../../sec_ded/encoder32/build-rvt
make clean
cd ../../../sec_ded/encoder64/build-rvt
make clean
cd ../../../sec_ded/decoder128/build-rvt
make clean
cd ../../../sec_ded/decoder32/build-rvt
make clean
cd ../../../sec_ded/decoder64/build-rvt
make clean
